# Generated by Django 5.0.4 on 2024-05-02 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_patient_blood_group_alter_patient_disease_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='Blood_group',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Disease',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Location',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Name',
            field=models.CharField(max_length=256),
        ),
    ]
